### ISSUE TITLE
Current version launching without asking for location information

### ISSUE THREAD

**Issue by Reynbow** [RedDuckss/CemuManager#1]
The current version does not ask for the location of the games and CEMU. It loads showing Mario Kart 8 and a couple broken games and all the buttons don't work.

**Comment by RedDuckss** [comment]
Oops! That's because I accidentally uploaded a release that had data in it 😅 (this is actually my first time releasing anything). You can fix it by going in to `data/cache` and deleting both files there.

I'm not currently at my house, so I can't edit the release at the moment. I have made a note on the release page about this issue, though.
