### ISSUE TITLE
Games are not loaded if http://thegamesdb.net/ is down

### ISSUE THREAD

**Issue by MrIlliteracy** [RedDuckss/CemuManager#5]
[http://thegamesdb.net/](http://thegamesdb.net/) is where covers etc. are gotten from.

Just listing it as an issue for now even though we are aware.

**Comment by RedDuckss** [comment]
In the next release box art will be delivered from http://gametdb.com, and backgrounds (a change in the next release) will still come from http://thegamesdb.net. I will be (hopefully) scraping both http://gametdb.com and http://thegamesdb.net for the relevant data, and saving everything locally (images as base64 strings), to serve everything offline. This should remove any and all need for the internet and online APIs. However this cannot happen until  http://thegamesdb.net comes back online.

**Comment by RedDuckss** [comment]
Just an update, storing all relevant data to a local file would increase the applications size from 40MB to well over 2GB due to the length of the base64 strings of the HD images. Because of this we are back to using the online API and are going to add default data in the event that data cannot be pulled.

**Comment by MatrixTunnel** [comment]
Maybe you should try using lower resolution pictures since some people might have really slow internet.  Depending on the size, you might still be able to use local base64 strings

**Comment by MrIlliteracy** [comment]
@MatrixTunnel ehhhhhh, 6k images is about 2.5GB for standard resolutions in base64

**Comment by MatrixTunnel** [comment]
What if you didn't have an internet connection at all then?  It still would break

**Comment by MrIlliteracy** [comment]
? Currently, if the site is down or if you don't have an internet connection, it would break. We're not going to have all the images offline. We're going to have default images and only load if we can.

**Comment by RedDuckss** [comment]
In a future release we are going to be adding in default and placeholder data for users with spotty or no internet connection. This was the plan since day one, and was supposed to be in the initial release, but other things took priority. There will also be reload features for the games in order to download and reload the data in the event that you did not have internet connection.

**Comment by RedDuckss** [comment]
Also as a side note, the 6k number mentioned by @MrIlliteracy is not an exaggeration. We would have to encode and store base64 strings for an exact total of 5152 images, which we calculated to be around 2.5GB alone.

**Comment by MatrixTunnel** [comment]
Ah ok.  Sounds like a plan

**Comment by RedDuckss** [comment]
Place holder content for all data, as well as placeholder background and box art has been added to the dev branch. CemuManager will now default to these values if none can be found.

**Comment by RedDuckss** [comment]
Issue is now fixed, moved away from http://thegamesdb.net/ as a dependency.
